export const TOGGLE_ADD_TODO = "TOGGLE_ADD_TODO";
export const ADD_NEW_TODO_REQUEST = "ADD_NEW_TODO_REQUEST";
export const ADD_NEW_TODO_REQUEST_SUCCESS = "ADD_NEW_TODO_REQUEST_SUCCESS";
export const ADD_NEW_TODO_REQUEST_FAILED  = "ADD_NEW_TODO_REQUEST_FAILED";
export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";
export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const HIDE_EDIT_MODAL = "HIDE_EDIT_MODAL";
export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_FAILED = "EDIT_TODO_FAILED";
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";
export const SHOW_DELETE_MODAL = "SHOW_DELETE_MODAL";
export const HIDE_DELETE_MODAL = "HIDE_DELETE_MODAL";

